"""ProofObligation — a logical formula to be discharged by Z3."""
from __future__ import annotations
from dataclasses import dataclass, field


@dataclass
class ProofObligation:
    """A single proof obligation generated by a Hoare proof rule."""
    formula: str          # logical formula as a string (Python/Z3 expression)
    description: str      # human-readable explanation
    structure_type: str   # "sequence" | "selection" | "iteration" | "atom"
    line_hint: int | None = None
    variables: list[str] = field(default_factory=list)
